from django.urls import path

from apps.tools.api import (
    upload_average_price_per_lesson_student,
    get_is_student_in_group_on_discipline,
    build_link_for_join_to_forming_group,
    forming_groups_for_join,
    student_to_forming_group,
    send_nothing_fit,
    add_hh_payment_by_amo_view,
    get_teacher_lesson_for_report,
    get_course_themes_view,
    send_lesson_report, upload_days_with_wrong_comment, reload_corrected_comments,
)

urlpatterns = [
    path('send_lesson_report/', send_lesson_report,
         name='send_lesson_report'),
    path('get_course_themes_view/', get_course_themes_view,
         name='get_course_themes_view'),
    path('get_forming_groups_for_join/',
         forming_groups_for_join,
         name='get_forming_groups_for_join'),
    path('get_teacher_lesson_for_report/',
         get_teacher_lesson_for_report,
         name='get_teacher_lesson_for_report'),
    path('student_to_forming_group/',
         student_to_forming_group,
         name='student_to_forming_group'),
    path('get_is_student_in_group_on_discipline/',
         get_is_student_in_group_on_discipline,
         name='get_is_student_in_group_on_discipline'),
    path('send_nothing_fit/',
         send_nothing_fit,
         name='send_nothing_fit'),
    path('build_link_for_join_to_forming_group/',
         build_link_for_join_to_forming_group,
         name='build_link_for_join_to_forming_group'),
    path('add_hh_payment_by_amo/',
         add_hh_payment_by_amo_view,
         name='add_hh_payment_by_amo'),
    path('upload_average_price_per_lesson_student/',
         upload_average_price_per_lesson_student,
         name='upload_average_price_per_lesson_student'),
    path('upload_days_with_wrong_comment/',
         upload_days_with_wrong_comment,
         name='upload_days_with_wrong_comment'),
    path('reload_corrected_comments/',
         reload_corrected_comments,
         name='reload_corrected_comments'),
]
